/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as NewPostRouteImport } from './routes/new-post'
import { Route as MeRouteImport } from './routes/me'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FastRouteImport } from './routes/fast'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostDocumentIdRouteImport } from './routes/post.$documentId'
import { Route as LearnVideoIdRouteImport } from './routes/learn.$videoId'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPostRoute = NewPostRouteImport.update({
  id: '/new-post',
  path: '/new-post',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FastRoute = FastRouteImport.update({
  id: '/fast',
  path: '/fast',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostDocumentIdRoute = PostDocumentIdRouteImport.update({
  id: '/post/$documentId',
  path: '/post/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnVideoIdRoute = LearnVideoIdRouteImport.update({
  id: '/learn/$videoId',
  path: '/learn/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/fast': typeof FastRoute
  '/feed': typeof FeedRoute
  '/me': typeof MeRoute
  '/new-post': typeof NewPostRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/upgrade': typeof UpgradeRoute
  '/learn/$videoId': typeof LearnVideoIdRoute
  '/post/$documentId': typeof PostDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/fast': typeof FastRoute
  '/feed': typeof FeedRoute
  '/me': typeof MeRoute
  '/new-post': typeof NewPostRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/upgrade': typeof UpgradeRoute
  '/learn/$videoId': typeof LearnVideoIdRoute
  '/post/$documentId': typeof PostDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/fast': typeof FastRoute
  '/feed': typeof FeedRoute
  '/me': typeof MeRoute
  '/new-post': typeof NewPostRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/upgrade': typeof UpgradeRoute
  '/learn/$videoId': typeof LearnVideoIdRoute
  '/post/$documentId': typeof PostDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/fast'
    | '/feed'
    | '/me'
    | '/new-post'
    | '/sign-in'
    | '/sign-up'
    | '/upgrade'
    | '/learn/$videoId'
    | '/post/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/fast'
    | '/feed'
    | '/me'
    | '/new-post'
    | '/sign-in'
    | '/sign-up'
    | '/upgrade'
    | '/learn/$videoId'
    | '/post/$documentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/fast'
    | '/feed'
    | '/me'
    | '/new-post'
    | '/sign-in'
    | '/sign-up'
    | '/upgrade'
    | '/learn/$videoId'
    | '/post/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FastRoute: typeof FastRoute
  FeedRoute: typeof FeedRoute
  MeRoute: typeof MeRoute
  NewPostRoute: typeof NewPostRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UpgradeRoute: typeof UpgradeRoute
  LearnVideoIdRoute: typeof LearnVideoIdRoute
  PostDocumentIdRoute: typeof PostDocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-post': {
      id: '/new-post'
      path: '/new-post'
      fullPath: '/new-post'
      preLoaderRoute: typeof NewPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fast': {
      id: '/fast'
      path: '/fast'
      fullPath: '/fast'
      preLoaderRoute: typeof FastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$documentId': {
      id: '/post/$documentId'
      path: '/post/$documentId'
      fullPath: '/post/$documentId'
      preLoaderRoute: typeof PostDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$videoId': {
      id: '/learn/$videoId'
      path: '/learn/$videoId'
      fullPath: '/learn/$videoId'
      preLoaderRoute: typeof LearnVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FastRoute: FastRoute,
  FeedRoute: FeedRoute,
  MeRoute: MeRoute,
  NewPostRoute: NewPostRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UpgradeRoute: UpgradeRoute,
  LearnVideoIdRoute: LearnVideoIdRoute,
  PostDocumentIdRoute: PostDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
